[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.9.10"
version_files = [
    'pyproject.toml:version',
    '.version'
]
tag_format = "v$version"
annotated_tag = true
update_changelog_on_bump = true
