# Generated by Django 4.0.4 on 2022-05-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconsent',
            name='accounts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consent', serialize=False, to='accounts.accounts'),
        ),
    ]
