# Generated by Django 4.0.4 on 2022-05-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deviceconsent_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='resolution',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_height',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='screen_width',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
