---
- hosts: all
  become: yes
  remote_user: root
  vars_files:
    - vars/docker.yml
    - vars/database.yml
  roles:
    - geerlingguy.docker
    - geerlingguy.postgres

  pre_tasks:
    - name: "install postgres packages"
      apt:
        pkg:
          - postgresql-client-common
  tasks:
    - name: Install docker
      import_role:
        name: geerlingguy.docker
    - name: Install Postgres SQL Database
      import_role:
        name: geerlingguy.postgres
