---
- hosts: localhost
  become: yes
  vars_files:
    - vars/docker.yml
  roles:
    - role: roles/geerlingguy.docker

  pre_tasks:
    - name: add python 3 ppa
      ansible.builtin.apt_repository:
        repo: 'ppa:deadsnakes/ppa'

  tasks:
    - name: "Install postgres cli client"
      apt:
        pkg:
          - python3.10
          - python3.10-dev
          - python3-pip

    - name: "install postgres packages"
      apt:
        - postgresql-client-common
