---
- hosts: localhost
  become: yes
  vars_files:
    - vars/docker.yml
  roles:
    - role: roles/geerlingguy.docker
    - role: roles/geerlingguy.postgresql

  tasks:
    - name: "install postgres packages"
      apt:
        pkg:
          - postgresql-client-common
        lock_timeout: 180
