---
- hosts: all
  become: yes
  vars_files:
    - vars/docker.yml
  roles:
    - geerlingguy.docker
    - geerlingguy.postgres

  tasks:
    - name: "install postgres packages"
      apt:
        pkg:
          - postgresql-client-common
        lock_timeout: 180
