name: Continuous Integration - Tests

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install pipenv tox
      # Runs a set of commands using the runners shell
      - name: Run tox
        run: |
          tox -r
