name: Ansible Provisioning Tasks

on:
  workflow_dispatch:
    inputs:
      app_env:
        description: Application Environment
        required: true
        type: choice
        options:
          - prod
          - staging
      db_password:
        description: Database password
        required: true
        type: string
      deploy_servers:
        description: comma separated list of ip addresses
        type: string

jobs:
  server_provisioning:
    runs-on: ubuntu-20.04
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: setup.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: ${{ github.event.inputs.deploy_servers }}
          options: |
            --extra-vars db_password=${{ github.event.inputs.db_password }}
            --verbose
